### PR TITLE
Implement IServiceProviderFactory for easy integration and update README

### PR DESCRIPTION
**Pull request by DaniilSokolyuk**
Implement IServiceProviderFactory for easy integration and update README (from my legacy https://github.com/DaniilSokolyuk/DS.Unity.Extensions.DependencyInjection)

### CODE REVIEW

**Comment by ENikS** [comment]
Ты не хочешь добавить [Sample Project](https://github.com/unitycontainer/examples) с примером как правильно использовать?

**Comment by DaniilSokolyuk** [comment]
:)
Давай

**Comment by ENikS** [comment]
I'll release your addition in v1.0.1 in a few

**Comment by ENikS** [comment]
https://www.nuget.org/packages/Unity.Microsoft.DependencyInjection/1.0.1

**Comment by ENikS** [comment]
Hey, thank you for your help!
Thanks to you this is most complete package so far.

You are welcome to contribute more if you ever have free time.

(Do not have cyrillic keyboard here so writing in english)

**Pull request merged**
